### ISSUE TITLE
NetBSD lint

### ISSUE THREAD

**Issue by rillig** [mcandre/linters#124]
NetBSD lint supports traditional C, C90, and the commonly used parts of C99 and C11. It can treat `bool` as a non-arithmetic data type.

https://man.NetBSD.org/lint.1
https://github.com/NetBSD/src/tree/trunk/usr.bin/xlint/lint1/README.md

**Comment by mcandre** [comment]
That's better than ol' splint, which never managed to fully grasp C90, let alone C17.
