### ISSUE TITLE
make --warn-undefined-variables

### ISSUE THREAD

**Issue by rillig** [mcandre/linters#125]
This option probably only applies to GNU make, not to [make](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/make.html) in general.

**Comment by mcandre** [comment]
Does bmake offer a similar flag?

What's hilarious is that the POSIX spec specifically encourages (as of Issue 8/D3, possibly earlier) make implementations to offer such a flag. But neither requires it or even recommends a convention for the name of the flag :P

**Comment by rillig** [comment]
No, bmake doesn't offer anything similar. One place where undefined variables are always forbidden are in conditions:

~~~text
.if ${UNDEF} == "expected value"     # runtime error
.if "${UNDEF}" == "ok"               # OK due to the surrounding quotes
~~~

But other than that, there is no modifier `${UNDEF:!!}` that would ensure that a variable is defined. Maybe it's possible to define a [custom dynamic modifier](https://github.com/NetBSD/src/blob/netbsd-10/usr.bin/make/unit-tests/varmod-indirect.mk) that can be used in the form `${UNDEF:${M_MustBeDefined}}`, but I haven't tried to implement that idea.

POSIX cannot specify the name `--warn-undefined-variables` as it [does not specify](https://pubs.opengroup.org/cgi/kman4.cgi?value=getopt_long) GNU's `getopt_long` anywhere. Prescribing a particular name is not possible since the many implementations of `make` (for example [BSD](https://man.netbsd.org/make.1), [GNU](https://www.gnu.org/software/make/manual/html_node/Options-Summary.html), [SunPro](https://schilytools.sourceforge.net/man/man1/make.1s.html)) are already using most of the available option letters in incompatible ways.

**Comment by mcandre** [comment]
Interesting.

In theory, POSIX could one day extend `-n` behavior beyond parsing, to include similar checks.

**Comment by mcandre** [comment]
Yeah, I'll mark that flag as GNU specific. Good catch.
