### ISSUE TITLE
Add web-puc

### ISSUE THREAD

**Issue by fulldecent** [mcandre/linters#23]
May I recommend the addition of web-puc. This project tests web projects (HTML, PHP, Ruby, Python, ..., anything that eventually outputs HTML) to ensure that they are using the latest version of JQuery and Bootstrap and some other libraries.

**Comment by mcandre** [comment]
Pull requests accepted, just insert it thar in the readme

**Comment by fulldecent** [comment]
Thank you, added right thurr.
