### ISSUE TITLE
Awesome Linters List

### ISSUE THREAD

**Issue by arbox** [mcandre/linters#35]
Hi Andrew,

you've compiled an awesome list! Thank you!

Did you think about turning this list into an official Awesome List (https://github.com/sindresorhus/awesome)?

I could help you and share my experience if you need to :smiley:

**Comment by mcandre** [comment]
I see that awesome lists already links to https://github.com/mre/awesome-static-analysis , which appears to be another well researched list. If you'd like to copy some items from this list to that one, be my guest, just cite this as one source I suppose.
