### ISSUE TITLE
banned.h link is dead

### ISSUE THREAD

**Issue by MrZoraman** [mcandre/linters#36]

**Comment by mcandre** [comment]
If someone can find a better URL for banned.h, let's open a pull request to fix the URL.

If someone can confirm that the banned.h experiment is dead, we can leave a deprecation notice by the banned.h section in our README.

**Comment by MrZoraman** [comment]
From a little bit of searching, it seems like banned.h has been forgotten about since ~2012. This is the best I could find... https://github.com/Microsoft/ChakraCore/blob/master/lib/Common/Banned.h
