### ISSUE TITLE
Collaborate on awesomes-static-analysis?

### ISSUE THREAD

**Issue by mre** [mcandre/linters#43]
Hey @mcandre,

I found your project through an [article on embeddedartistry.com](https://embeddedartistry.com/blog/2018/3/29/improving-our-software-with-5-lightweight-processes-you-can-adopt-this-month).
Looks like you have compiled a great list of resources over here. Do you want to join forces and become a co-maintainer of [awesome-static-analysis](https://github.com/mre/awesome-static-analysis/)?

**Comment by mcandre** [comment]
I appreciate all the Awesome lists :)

I think I will still keep my list of linter here, though of course I welcome PR’s between our projects!

**Comment by mre** [comment]
Cool, makes sense.
